wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720449496
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 23
      4: 3.12.1
      5: 0.17.4
      6: 4.36.2
      8:
      - 1
      - 3
      - 8
      13: windows-amd64
